# packages/dvla.yaml
#
# DVLA MOT & Tax Expiry Sensors
# Modern template syntax with entity_ids aligned to legacy automations

homeassistant:
  customize: {}

template:
  - sensor:
      # MOT Expiry Sensors
      - name: "BMW MOT Expiry"
        unique_id: bmw_mot_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_pe69jnx_motexpirydate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_pe69jnx_motexpirydate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Kuga MOT Expiry"
        unique_id: kuga_mot_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_mk18dhd_motexpirydate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_mk18dhd_motexpirydate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Tipo MOT Expiry"
        unique_id: tipo_mot_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_wm17wlk_motexpirydate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_wm17wlk_motexpirydate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Fiesta MOT Expiry"
        unique_id: fiesta_mot_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_kl10loz_motexpirydate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_kl10loz_motexpirydate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Kuga Hybrid MOT Expiry"
        unique_id: kuga2_mot_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_ng72omx_motexpirydate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_ng72omx_motexpirydate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      # Tax Expiry Sensors
      - name: "BMW Tax Expiry"
        unique_id: bmw_tax_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_pe69jnx_taxduedate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_pe69jnx_taxduedate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Kuga Tax Expiry"
        unique_id: kuga_tax_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_mk18dhd_taxduedate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_mk18dhd_taxduedate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Tipo Tax Expiry"
        unique_id: tipo_tax_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_wm17wlk_taxduedate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_wm17wlk_taxduedate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Fiesta Tax Expiry"
        unique_id: fiesta_tax_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_kl10loz_taxduedate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_kl10loz_taxduedate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days

      - name: "Kuga Hybrid Tax Expiry"
        unique_id: kuga2_tax_expiry
        state: >-
          {% set expiry = as_datetime(states('sensor.dvla_ng72omx_taxduedate')) %}
          {% if expiry %}
            {{ (expiry.date() - now().date()).days }}
          {% else %}
            0
          {% endif %}
        icon: >-
          {% set expiry = as_datetime(states('sensor.dvla_ng72omx_taxduedate')) %}
          {% if expiry and (expiry.date() - now().date()).days >= 28 %}
            mdi:check-circle
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: days
